### 김중헌 교수 Github 교육 자료
- https://github.com/joongheon/tutorial-deeplearning-basics

In [23]:
!pip install tensorflow==1.5.0

In [3]:
import tensorflow as tf
print(tf.__version__)

node1 = tf.constant(3, dtype=tf.int32)
node2 = tf.constant(5, dtype=tf.int32)
node3 = tf.add(node1, node2)

print('node1 + node2 = ', node3)

1.5.0
node1 + node2 =  Tensor("Add_1:0", shape=(), dtype=int32)


In [4]:
import tensorflow as tf
print(tf.__version__)

node1 = tf.constant(3, dtype=tf.int32)
node2 = tf.constant(5, dtype=tf.int32)
node3 = tf.add(node1, node2)

sess = tf.Session()
print('node1 + node2 = ', sess.run(node3))
sess.close()

1.5.0
node1 + node2 =  8


In [5]:
import tensorflow as tf

node1 = tf.constant(3, dtype=tf.int32)
node2 = tf.constant(5, dtype=tf.int32)
node3 = tf.add(node1, node2)

with tf.Session() as sess:
    print('node1 + node2 = ', sess.run(node3))

node1 + node2 =  8


In [7]:
import tensorflow as tf

a = tf.placeholder(tf.int32, shape=(3,1))
b = tf.placeholder(tf.int32, shape=(1,3))
c = tf.matmul(a, b)

with tf.Session() as sess:
    print(sess.run(c, feed_dict={a: [[1], [2], [3]], b: [[1,2,3]]}))

[[1 2 3]
 [2 4 6]
 [3 6 9]]
