In [1]:
!pip install tensorflow==1.5.0

     |████████████████████████████████| 44.4MB 95kB/s 
     |████████████████████████████████| 3.0MB 45.3MB/s 
     |████████████████████████████████| 890kB 41.4MB/s 
  Created wheel for html5lib: filename=html5lib-0.9999999-cp36-none-any.whl size=107220 sha256=c7da9ac8bcc51aa21cf646d82259575fc9a3b97795228c34fd3ce5dc89d99c7c
  Stored in directory: /root/.cache/pip/wheels/50/ae/f9/d2b189788efcf61d1ee0e36045476735c838898eef1cad6e29
Successfully built html5lib
  Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
  Found existing installation: bleach 3.1.5
    Uninstalling bleach-3.1.5:
      Successfully uninstalled bleach-3.1.5
  Found existing installation: tensorflow 2.2.0
    Uninstalling tensorflow-2.2.0:
      Successfully uninstalled tensorflow-2.2.0


# XOR with Binary Classification

In [5]:
import tensorflow as tf
# X, Y 입력
x_data = [[0,0], [0,1], [1,0], [1,1]]
y_data = [[0], [1], [1], [0]]
X = tf.placeholder('float', [None, 2])
Y = tf.placeholder('float', [None, 1])

# W, b 변수
W = tf.Variable(tf.random_normal([2, 1]))
b = tf.Variable(tf.random_normal([1]))

# model, cost, train
model = tf.sigmoid(tf.matmul(X, W) + b)
cost = tf.reduce_mean((-1)*Y*tf.log(model) + (-1)*(1.0-Y)*tf.log(1.0-model))
train = tf.train.GradientDescentOptimizer(0.1).minimize(cost)

# predict, accuracy
prediction = tf.cast(model > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, Y), dtype=tf.float32))

# Session 생성
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # Training
    for step in range(20001):
        c, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 2000 == 0:
            print(step, c)
    # Test
    m, p, a = sess.run([model, prediction, accuracy], feed_dict={X: x_data, Y: y_data})
    print('Model:\n', m, '\nPrediction:\n', p, '\nAccuarcy:\n', a)

# 파라미터 : W, b 
# 하이퍼 파라미터 : learning rate, traing 횟수 등
# 하이퍼 파라미터 튜닝 필요

0 1.7485576
2000 0.6931472
4000 0.6931472
6000 0.6931472
8000 0.6931472
10000 0.6931472
12000 0.6931472
14000 0.6931472
16000 0.6931472
18000 0.6931472
20000 0.6931472
Model:
 [[0.5]
 [0.5]
 [0.5]
 [0.5]] 
Prediction:
 [[0.]
 [0.]
 [0.]
 [0.]] 
Accuarcy:
 0.5


# XOR with ANN

In [8]:
import tensorflow as tf
# X, Y 입력
x_data = [[0,0], [0,1], [1,0], [1,1]]
y_data = [[0], [1], [1], [0]]
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W_h = tf.Variable(tf.random_normal([2, 3]))
b_h = tf.Variable(tf.random_normal([3]))
H1 = tf.sigmoid(tf.matmul(X, W_h) + b_h)

W_o = tf.Variable(tf.random_normal([3, 1]))
b_o = tf.Variable(tf.random_normal([1]))

model = tf.sigmoid(tf.matmul(H1, W_o) + b_o)
cost = tf.reduce_mean((-1)*Y*tf.log(model) + (-1)*(1.0-Y)*tf.log(1.0-model))
train = tf.train.GradientDescentOptimizer(0.1).minimize(cost)

# predict, accuracy
prediction = tf.cast(model > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, Y), dtype=tf.float32))

# Session 생성
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # Training
    for step in range(20001):
        c, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 2000 == 0:
            print(step, c)
    # Test
    m, p, a = sess.run([model, prediction, accuracy], feed_dict={X: x_data, Y: y_data})
    print('Model:\n', m, '\nPrediction:\n', p, '\nAccuarcy:\n', a)

# 파라미터 : W, b 
# 하이퍼 파라미터 : learning rate, traing 횟수 등
# 하이퍼 파라미터 튜닝 필요

0 1.2675874
2000 0.22936356
4000 0.04729452
6000 0.024236096
8000 0.016044728
10000 0.011923276
12000 0.009459623
14000 0.007826909
16000 0.0066679246
18000 0.0058038025
20000 0.0051353825
Model:
 [[0.00501982]
 [0.993909  ]
 [0.9952258 ]
 [0.00460198]] 
Prediction:
 [[0.]
 [1.]
 [1.]
 [0.]] 
Accuarcy:
 1.0
