In [0]:
def same(x, y):
    return list(set(x) & set(y))

In [4]:
a = [1, 2, 3, 4, 5, 6]
b = [3, 4, 5, 6, 7, 8]
c = same(a, b)
c

[3, 4, 5, 6]

In [5]:
a, b = b, a
print(a, b)

[3, 4, 5, 6, 7, 8] [1, 2, 3, 4, 5, 6]


In [0]:
import numpy as np

In [7]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
b = np.array(a)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
c = [a, a, a]    # list of list
c

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [14]:
d = np.array(c)
print(d)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [15]:
d.shape    # ()가 없으면 속성, ()가 있으면 메소드, shape는 속성

(3, 10)

In [18]:
# 행 조회
d.shape[0]

3

In [20]:
# 열 조회
d.shape[1]

10

In [22]:
# 3 x 10 ---> 5 x 6
d = d.reshape(5, 6)
print(d)

[[0 1 2 3 4 5]
 [6 7 8 9 0 1]
 [2 3 4 5 6 7]
 [8 9 0 1 2 3]
 [4 5 6 7 8 9]]


In [23]:
d = d * 2
print(d)

[[ 0  2  4  6  8 10]
 [12 14 16 18  0  2]
 [ 4  6  8 10 12 14]
 [16 18  0  2  4  6]
 [ 8 10 12 14 16 18]]


In [24]:
d = 50 - d
print(d)

[[50 48 46 44 42 40]
 [38 36 34 32 50 48]
 [46 44 42 40 38 36]
 [34 32 50 48 46 44]
 [42 40 38 36 34 32]]


In [25]:
d = d / 5
print(d)

[[10.   9.6  9.2  8.8  8.4  8. ]
 [ 7.6  7.2  6.8  6.4 10.   9.6]
 [ 9.2  8.8  8.4  8.   7.6  7.2]
 [ 6.8  6.4 10.   9.6  9.2  8.8]
 [ 8.4  8.   7.6  7.2  6.8  6.4]]


In [27]:
d = d.round(0)
print(d)

[[10. 10.  9.  9.  8.  8.]
 [ 8.  7.  7.  6. 10. 10.]
 [ 9.  9.  8.  8.  8.  7.]
 [ 7.  6. 10. 10.  9.  9.]
 [ 8.  8.  8.  7.  7.  6.]]


In [0]:
# 배열은 1가지 자료형만 가질 수 있다