<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/title.png' width=500/><center>

# 학습 목표

- 배열 사이의 기본적인 연산을 수행할 수 있습니다.
- 전치 행렬의 의미를 이해합니다.
- Shuffling과 Samplig 개념을 이해하고 활용할 수 있습니다.
- 여러 배열을 하나로 연결할 수 있습니다.

# 3. 배열 연산

- 배열 사이의 더하기, 빼기, 곱하기, 나누기 등은 이해하기 쉽습니다.
- 하지만 행렬 곱, 행렬 합등의 연산은 악갼의 수학적 지식이 필요합니다.
- 행렬 연산은 선형 대수를 위한 것이므로 설명을 생략합니다.

In [0]:
# 라이브러리 불러오기
import numpy as np

## 3.1. 기본 연산

- 리스트와는 달리 각 요소 사이의 기본 연산이 가능합니다.
- 이런 연산이 목적으로 배열을 사용하기도 합니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/array_operator.png' width=500 align="left"/>

In [2]:
# 두 개의 2 x 2 형태의 2차원 배열 만들기
x = np.array([[1, 2], [3, 4]], dtype = np.int32)
y = np.array([[5, 6], [7, 8]], dtype = np.int32)

# 확인
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


**1) 배열 더하기**

- \+ 또는 **dp.add()** 함수를 사용합니다.

In [3]:
# 배열 더하기
print(x + y)

# 또는
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


**2) 배열 뺴기**

- \- 또는 **np.subtract()** 함수를 사용합니다.

In [4]:
# 배열 빼기
print(x - y)

# 또는
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


**3) 배열 곱하기**

- \* 또는 **np.multiply()** 함수를 사용합니다.

In [5]:
# 배열 곱하기
print(x * y)

# 또는
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


**4) 배열 나누기**

- \/ 또는 **np.divide()** 함수를 사용합니다.

In [6]:
# 배열 나누기
print(x / y)

# 또는
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


**5) 배열 제곱**

- \** 또는 **np.power()** 함수를 사용합니다.

In [7]:
# 배열 y 제곱
print(x ** y)

# 또는
print(np.power(x, y))

[[    1    64]
 [ 2187 65536]]
[[    1    64]
 [ 2187 65536]]


In [8]:
# 배열 제곱
print(x ** 2)

[[ 1  4]
 [ 9 16]]


In [9]:
# 배열 제곱
print(np.power(x, 2))

[[ 1  4]
 [ 9 16]]


**6) 배열 제곱근**

- **np.sqrt()** 함수를 사용합니다.

In [0]:
# 배열 제곱근
print(np.sqrt(x))

## 3.2. 리스트와 배열이 다른 점

- 리스트의 더하기 곱하기 연산은 배열의 더하기 곱하기 연산과 완전히 다릅니다.
- 예를 들어 리스트는 나눌 수 없지만 배열은 나눌 수 있습니다.

In [0]:
# 리스트와 배열 만들기
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [11]:
# 리스트 연산
print(python_list + python_list)
print(python_list * 3)

[1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [12]:
# 배열 연산
print(numpy_array + numpy_array)
print(numpy_array * 3)

[2 4 6]
[3 6 9]


In [13]:
# 리스트는 나누거나 제곱할 수 없음
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

print(weight / height ** 2)
#TypeError: unsupported operand type(s) for **: 'list' and 'int'

TypeError: ignored

In [14]:
# 배열은 요소끼리 나누거나 제곱할 수 있음
np_height = np.array(height)
np_weight = np.array(weight)

print(np_weight / np_height ** 2)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


## 3.3. 전치행렬

- **행과 열을 교환**하여 얻는 행렬을 전치행렬입니다.
- **주 대각선**을 축으로 하는 **반사 대칭**을 가하여 얻는 행렬입니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/matrix4.png' width=600 align="left"/>

In [15]:
# 1 x 4 형태의 2차원 배열 만들기
a = np.array([1, 2, 3, 4], ndmin = 2)

# 확인
print(a.shape)
print(a)

(1, 4)
[[1 2 3 4]]


In [16]:
# 전치행렬 
print(a.T)

[[1]
 [2]
 [3]
 [4]]


In [17]:
# 2 x 2 형태의 2차원 배열 만들기 
a = np.array([[1, 2], 
              [3, 4]])

# 확인
print(a)

[[1 2]
 [3 4]]


In [18]:
# 전치행렬
print(a.T)

[[1 3]
 [2 4]]


In [19]:
# 3 x 2 형태의 2차원 배열 만들기 
a = np.array([[1, 2], 
              [3, 4],
              [5, 6]])

# 확인
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
# 전치행렬
print(a.T)

[[1 3 5]
 [2 4 6]]


In [21]:
# 1차원 배열은 전치행렬이 의미가 없음
a = np.array([1, 2 ,3])
print(a)

[1 2 3]


In [22]:
# 전치행렬?
print(a.T)

[1 2 3]


## 3.4. Shuffle

- **np.random.shuffle()** 함수를 사용해 배열을 섞어 임의 순서의 배열을 얻을 수 있습니다.

**1) 1차원 배열 섞기**

- 우선 1차원 배열을 섞어봅시다.

In [0]:
# 1차원 배열 만들기
a = np.array([1, 2, 3, 4, 5])

In [25]:
# 배열 섞기
np.random.shuffle(a)
print(a)

[3 2 4 1 5]


**2) 2차원 배열 섞기**

- 모든 요소를 섞지는 못합니다.
- 단지 행 기준으로 섞어주며, 행 안의 요소는 섞이지 않습니다. 

In [0]:
# 2차원 배열 만들기
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [34]:
# 배열 섞기 --> 행은 섞이나, 열은 섞이지 않는다 --> 즉, 행 순서만 섞인다
np.random.shuffle(a)
print(a)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


**3) csv 파일 읽어와 섞기**

- 당연히 파일에서 데이터를 읽어와 만든 배열도 섞을 수 있습니다.

In [35]:
# 파일에서 데이터 가져오기
file_path = 'https://raw.githubusercontent.com/Jangrae/csv/master/Graduate_apply.csv'
data = np.genfromtxt(file_path, delimiter=",", names=True)

# 10개 확인
print(data[0:10])

[(0., 380., 3.61, 3.) (1., 660., 3.67, 3.) (1., 800., 4.  , 1.)
 (1., 640., 3.19, 4.) (0., 520., 2.93, 4.) (1., 760., 3.  , 2.)
 (1., 560., 2.98, 1.) (0., 400., 3.08, 2.) (1., 540., 3.39, 3.)
 (0., 700., 3.92, 2.)]


In [36]:
# Shuffle (이 셀을 Ctrl + Enter로 반복실행)
np.random.shuffle(data)

# 10개 확인
print(data[0:10])

[(0., 600., 3.63, 3.) (1., 740., 4.  , 3.) (0., 580., 3.8 , 2.)
 (0., 400., 3.35, 3.) (0., 500., 2.98, 3.) (0., 640., 3.86, 3.)
 (0., 500., 3.35, 2.) (0., 360., 3.  , 3.) (0., 300., 2.92, 4.)
 (0., 540., 3.28, 3.)]


**[참고] 리스트 섞기**

- 배열 뿐만이 아니라 리스트도 섞을 수 있습니다.

In [0]:
# 리스트 만들기
a = [1, 2, 3, 4, 5]

In [38]:
# 리스트 섞기
np.random.shuffle(a)
print(a)

[5, 2, 3, 4, 1]


**[참고] 두 배열 같은 순서로 섞기**

- 섞기는 임의의 순서로 이루어지므로 같은 요소를 갖는 두 배열의 섞인 결과가 달라집니다.
- 만일 두 배열을 갖는 순서로 섞으려고 한다면 약간의 트릭이 필요합니다.
- **np.arrange([시작,] 끝 [,스텝])** 형태로 임의의 정수를 갖는 1차원 배열을 만들 수 있습니다.

In [39]:
# np.arrange() 사용 예
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [40]:
# 두 개의 배열 만들기
a = np.arange(1, 11)
b = np.arange(11, 21)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [41]:
# 배열 형태 확인
print(a.shape)
print(a.shape[0])

(10,)
10


- 두 배열의 개수만큼 정수를 갖는 배열을 만들고 이 배열을 섞어줍니다.

In [42]:
# 요소 개수만큼 정수를 갖는 배열 만들기
s = np.arange(a.shape[0])
print(s)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
# 배열 섞기
np.random.shuffle(s)
print(s)

[3 1 2 6 7 5 4 0 9 8]


- 그리고 섞인 배열의 정수로 기존 두 배열을 조회하면 같은 순서로 섞인 결과가 됩니다.

In [44]:
# 기존 배열 섞기
a = a[s]
b = b[s]
print(a)
print(b)

[ 4  2  3  7  8  6  5  1 10  9]
[14 12 13 17 18 16 15 11 20 19]


In [84]:
# 내 생각: 두개 배열을 순서가 바뀌지 않게 shuffle 하기
a = np.arange(1, 11)
b = np.arange(11, 21)
print(a)
print(b)

c = np.c_[a, b]
print(c)

np.random.shuffle(c)
print(c)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]
 [10 20]]
[[ 9 19]
 [ 6 16]
 [ 8 18]
 [ 4 14]
 [ 3 13]
 [10 20]
 [ 2 12]
 [ 7 17]
 [ 1 11]
 [ 5 15]]


## 3.5. Sampling

- **np.random.choice()** 함수로 지정한 개수의 임의의 요소를 갖는 배열을 만들 수 있습니다.
- **np.random.choice(어디서, 얼마나, 어떻게)** 형식을 기억하세요.

In [45]:
file_path = 'https://raw.githubusercontent.com/Jangrae/csv/master/Graduate_apply.csv'
data = np.genfromtxt(file_path, delimiter=",", names=True)
data.shape

(400,)

In [49]:
# 임의의 4개 요소 추출
print(np.random.choice(data, 4))

[(0., 620., 3.09, 4.) (0., 620., 3.94, 4.) (0., 580., 2.88, 2.)
 (1., 660., 3.95, 2.)]


**[참고] 복원 추출과 비복원 추출**

- 복원 추출: 추출 된 요소을 다시 배열에 추가한 후 추출합니다.(기본값)
- 비복원 추출: 기존 배열 요소에서만 추출합니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/random_choice.png' width=500 align="left"/>

**1) 복원 추출**

- **np.arange(10)**는 0부터 9까지 정수를 갖는 배열을 만듭니다.
- np.arange() 함수는 유용하게 사용니 꼭 기억하세요.

In [50]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [51]:
print(np.random.choice(a, 4))

[4 3 4 5]


**2) 비복원 추출**

In [57]:
# 비복원추출 : 같은 값이 나올 수 없음
print(np.random.choice(a, 4, replace=False))

[1 0 5 3]


In [53]:
# 위 코드는 다음과 같음
print(np.random.choice(10, 4, replace=False))

[9 5 8 7]


## 3.6. Split

- 하나의 배열을 여러 배열로 나눌 수 있습니다.
- 머신러닝에서 하나의 데이터 셋에서 학습용, 검증용, 평가용 데이터로 분리할 때 많이 사용합니다.

In [58]:
file_path = 'https://raw.githubusercontent.com/Jangrae/csv/master/Graduate_apply.csv'
data = np.genfromtxt(file_path, delimiter=",", names=True)
data.shape

(400,)

In [0]:
# 100개씩 분할(Split)
s1, s2, s3, s4 = data[:100], data[100:200], data[200:300], data[300:]

In [60]:
# 갯수 확인
print(len(s1))
print(len(s2))
print(len(s3))
print(len(s4))

100
100
100
100


In [0]:
train, test = data[:300], data[300:]

In [63]:
print(train.shape)
print(test.shape)

(300,)
(100,)


In [61]:
# 내용 확인
print(s1)

[(0., 380., 3.61, 3.) (1., 660., 3.67, 3.) (1., 800., 4.  , 1.)
 (1., 640., 3.19, 4.) (0., 520., 2.93, 4.) (1., 760., 3.  , 2.)
 (1., 560., 2.98, 1.) (0., 400., 3.08, 2.) (1., 540., 3.39, 3.)
 (0., 700., 3.92, 2.) (0., 800., 4.  , 4.) (0., 440., 3.22, 1.)
 (1., 760., 4.  , 1.) (0., 700., 3.08, 2.) (1., 700., 4.  , 1.)
 (0., 480., 3.44, 3.) (0., 780., 3.87, 4.) (0., 360., 2.56, 3.)
 (0., 800., 3.75, 2.) (1., 540., 3.81, 1.) (0., 500., 3.17, 3.)
 (1., 660., 3.63, 2.) (0., 600., 2.82, 4.) (0., 680., 3.19, 4.)
 (1., 760., 3.35, 2.) (1., 800., 3.66, 1.) (1., 620., 3.61, 1.)
 (1., 520., 3.74, 4.) (1., 780., 3.22, 2.) (0., 520., 3.29, 1.)
 (0., 540., 3.78, 4.) (0., 760., 3.35, 3.) (0., 600., 3.4 , 3.)
 (1., 800., 4.  , 3.) (0., 360., 3.14, 1.) (0., 400., 3.05, 2.)
 (0., 580., 3.25, 1.) (0., 520., 2.9 , 3.) (1., 500., 3.13, 2.)
 (1., 520., 2.68, 3.) (0., 560., 2.42, 2.) (1., 580., 3.32, 2.)
 (1., 600., 3.15, 2.) (0., 500., 3.31, 3.) (0., 700., 2.94, 2.)
 (1., 460., 3.45, 3.) (1., 580., 3.46, 2

## 3.7. 배열 연결

- **np.r_[...]**를 사용해 여러 배열을 행으로 연결할 수 있습니다.
- **np.c_[...]**를 사용해 여러 배열을 열로 연결할 수 있습니다.

**1) 배열 만들기**

In [64]:
a1 = np.array(np.random.randint(1, 10, (3, 4)))
print(a1)

[[9 7 2 8]
 [2 5 5 1]
 [8 7 1 1]]


In [65]:
a2 = np.array(np.random.randint(1, 10, (3, 4)))
print(a2)

[[9 8 4 7]
 [5 5 8 4]
 [1 5 7 9]]


In [78]:
a3 = np.array(np.random.randint(1, 10, (3, 4)))
print(a3)

[[8 1 4 2]
 [6 5 6 9]
 [2 5 2 4]]


**2) 행에 연결**

In [72]:
print(np.r_[a1, a2])

[[9 7 2 8]
 [2 5 5 1]
 [8 7 1 1]
 [9 8 4 7]
 [5 5 8 4]
 [1 5 7 9]]


In [79]:
print(np.r_[a1, a2, a3])

[[9 7 2 8]
 [2 5 5 1]
 [8 7 1 1]
 [9 8 4 7]
 [5 5 8 4]
 [1 5 7 9]
 [8 1 4 2]
 [6 5 6 9]
 [2 5 2 4]]


**3) 열에 연결**

In [69]:
print(np.c_[a1, a2])

[[9 7 2 8 9 8 4 7]
 [2 5 5 1 5 5 8 4]
 [8 7 1 1 1 5 7 9]]


In [80]:
print(np.c_[a1, a2, a3])

[[9 7 2 8 9 8 4 7 8 1 4 2]
 [2 5 5 1 5 5 8 4 6 5 6 9]
 [8 7 1 1 1 5 7 9 2 5 2 4]]


## <center>수고하셨습니다.</center>
<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/end.png' width=200/></center>