<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/title.png' width=500/><center>

<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/practice.png' width=300/></center>

# 실습 목표

- 1, 2, 3차원 배열을 만들 수 있습니다.
- 배열의 크기(Shape)를 확인할 수 있습니다.
- Reshape 기능으로 배열 크기를 바꿀 수 있습니다.

# P1. [실습] 배열 만들기

In [0]:
# 라이브러리 불러오기
import numpy as np

1) a 리스트를 사용해 **np_01** 배열을 생성하세요

In [4]:
# 리스트 만들기
a = [1, 2, 3, 4, 5, 6]

# 배열 만들기
np_01 = np.array(a)

# 확인
print(np_01)

[1 2 3 4 5 6]


2) np_01의 크기를 확인하세요.

In [5]:
# 배열 크기 확인
np_01.shape

(6,)

3) np_01의 크기를 **(6, 1)**로 변환하여 **np_02**에 넣으세요.

In [7]:
# 6 x 1 형태로 변경
np_02 = np_01.reshape(6,1)
print(np_02)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


4) np_01의 크기를 **(1, 6)**로 변환하여 **np_03**에 넣으세요.

In [8]:
# 1 x 6 형태로 변경
np_03 = np_01.reshape(1, 6)
print(np_03)

[[1 2 3 4 5 6]]


5) np_01의 크기를 **(-1, 2)**로 변환하여 **np_04**에 넣으세요.

In [10]:
# -1 x 2 형태로 변경
np_04 = np_01.reshape(-1, 2)
print(np_04)

[[1 2]
 [3 4]
 [5 6]]


6) np_01, np_02, np_03, np_04의 **크기**와 **값**을 확인하세요.

In [11]:
# np_01 크기 확인
print(np_01.shape)

# np_01 값 확인
print(np_01)

(6,)
[1 2 3 4 5 6]


In [12]:
# np_02 크기 확인
print(np_02.shape)

# np_02 값 확인
print(np_02)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [13]:
# np_03 크기 확인
print(np_03.shape)

# np_03 값 확인
print(np_03)

(1, 6)
[[1 2 3 4 5 6]]


In [14]:
# np_04 크기 확인
print(np_04.shape)

# np_04 값 확인
print(np_04)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


7) 랜덤값으로 채운 **12 x 6** 형태의 2차원 배열을 생성하여 **np_sample** 변수로 선언하세요.

In [26]:
# 12 x 6 형태의 2차원 배열 만들기
np_sample = np.random.randint(-24, 24, (12, 6))

# 크기 확인
print(np_sample.shape)

# 값 확인
print(np_sample)

(12, 6)
[[-15 -14  -7  21 -18 -22]
 [-11 -11  -6  -9   8   0]
 [ 22 -10  10   6   9   9]
 [ -7  -4   8 -15  -7 -11]
 [ 18 -13   5  18  -9 -20]
 [ 19 -15  -6  -3  12   4]
 [ -3   7 -23  -1 -14  16]
 [-10   8 -24  10  -1   9]
 [ 19  13   8   8 -24   0]
 [ 10 -22  -4  19  22   8]
 [ 14 -17  -1   5   9 -15]
 [ 20   0   5 -24 -24  21]]


8) np_sample 배열을 24 x ? 형태로 변경하세요.

In [27]:
# 24 x ? 형태의 2차원 배열 만들기
np_sample2 = np_sample.reshape(24, -1)

# 크기 확인
print(np_sample2.shape)

# 값 확인
print(np_sample2)

(24, 3)
[[-15 -14  -7]
 [ 21 -18 -22]
 [-11 -11  -6]
 [ -9   8   0]
 [ 22 -10  10]
 [  6   9   9]
 [ -7  -4   8]
 [-15  -7 -11]
 [ 18 -13   5]
 [ 18  -9 -20]
 [ 19 -15  -6]
 [ -3  12   4]
 [ -3   7 -23]
 [ -1 -14  16]
 [-10   8 -24]
 [ 10  -1   9]
 [ 19  13   8]
 [  8 -24   0]
 [ 10 -22  -4]
 [ 19  22   8]
 [ 14 -17  -1]
 [  5   9 -15]
 [ 20   0   5]
 [-24 -24  21]]


## <center>수고하셨습니다.</center>
<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/end.png' width=200/></center>