<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/title.png' width=500/><center>

<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/practice.png' width=300/></center>

# 실습 목표

- 배열 크기를 확인할 수 있습니다.
- 배열을 분할할 수 있습니다.
- 배열 요소를 섞을 수 있습니다.
- 임의 요소를 샘플링할 수 있습니다.

# P3. [실습] 배열 연산

In [0]:
# 라이브러리 불러오기
import numpy as np 

In [0]:
# 파일에서 읽어와 배열 만들기
file_path = 'https://raw.githubusercontent.com/Jangrae/csv/master/Graduate_apply.csv'
apply = np.genfromtxt(file_path, delimiter = ',', names = True)

1) apply의 요소 개수를 확인하세요.

In [3]:
# 배열 크기 확인
apply.shape

(400,)

2) apply의 요소들 중 **0 ~ 300** 까지의 행은 **train** 변수에, **301 ~ 마지막** 까지의 행은 **test** 변수에 담으세요.

In [6]:
# 배열 분할
train, test = apply[:301], apply[301:]

# 배열 크기 확인
print(train.shape)
print(test.shape)

(301,)
(99,)


3) **train**에 담겨있는 데이터를 **suffle()** 메소드로 섞은 후 **상위 5개** 요소를 조회하세요.

In [29]:
# 배열 섞기
np.random.shuffle(train)
print(train[:5])

[(1., 660., 4.  , 2.) (0., 680., 3.64, 3.) (1., 680., 2.96, 3.)
 (1., 560., 2.98, 1.) (0., 580., 4.  , 3.)]


In [31]:
print(train[:5])
train2 = train[:100]
np.random.shuffle(train2)
print(train2[:5])

[(1., 560., 3.59, 2.) (1., 580., 3.46, 2.) (0., 760., 3.35, 3.)
 (0., 600., 3.13, 2.) (0., 520., 3.12, 2.)]
[(1., 540., 3.84, 2.) (0., 580., 3.69, 1.) (0., 600., 3.32, 2.)
 (1., 600., 3.56, 2.) (0., 460., 3.15, 4.)]


4) **0 ~ 100** 까지의 숫자를 **1차원** 배열 **arr**로 선언하세요.

In [27]:
# 임의 정수를 갖는 배열 만들기
arr = np.arange(0, 101)

# 크기 확인
print(arr.shape)

(101,)


5) 4번에서 만든 **arr**에서 10개의 값을 무작위로 추출하세요. 단, **비복원 추출** 방식을 사용하세요.

In [15]:
#  비복원 추출
print(np.random.choice(arr, 10, replace=False))

[48 20 52 23 42 96 75 44 63 97]


6) arr에서 10개의 값을 무작위로 추출하세요. 단, **복원 추출** 방식을 사용하세요.

In [26]:
# 복원 추출
print(np.random.choice(arr, 20))

[61  9 69 61 67  9  8 21 29 10 43 18 83 26 31 52 82 59  7 55]


7) arr에서 5개의 값을 무작위로 추출하세요. 단, **다른 컴퓨터**에서도 **동일한 값**으로 추출되도록 코드를 작성하세요.

In [22]:
# Seed 사용
np.random.seed(20200513)
print(np.random.choice(arr, 5))

[41 66 77 11  8]


## <center>수고하셨습니다.</center>
<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/end.png' width=200/></center>